### ISSUE TITLE
(Bug): When you restart the bot, moonlinkjs resuming the music but the `<player>.playing` variable returns false

### ISSUE THREAD

**Issue by Alexinhans** [1Lucas1apk/moonlink.js#103]
**Describe the bug**
When you restart the bot, moonlinkjs resuming the music but the `<player>.playing` variable returns false.  Even if the music continues where it left off, the `trackEnd` event gets emitted.

**To Reproduce**
1. Set manager options `resume` and `autoResume` to true
2. Play a music using `<player>.play()` by checking with `<player>.playing`
3. Restart the bot
4. Play a music again
5. The manager will cause an unexpected behavior like the music gets skipped, the music player is undefined, `<player>.playing` returns false.

**Expected behavior**
Players shouldnt be deleted from the manager, `<player>.playing` should return true and trackEnd event shouldnt be emited

**Screenshots**
![Capture](https://github.com/Ecliptia/moonlink.js/assets/103999185/de4bd0f2-d6f2-49fb-8b1f-f3ebca6dba29)
![Capture1](https://github.com/Ecliptia/moonlink.js/assets/103999185/20c8cd80-f030-4744-ba4c-2b49555c21c0)

**Additional context**
moonlinkjs version: 3.6.4
lavalink version: latest v4

**Comment by 1Lucas1apk** [comment]
Moonlink.js v3 will no longer have updates, wait for the rewrite

**Comment by 1Lucas1apk** [comment]
More information on the support server in announcement

**Comment by Alexinhans** [comment]
__

> Moonlink.js v3 will no longer have updates, wait for the rewrite

You should add something like it's outdated and won't get updates anymore until I rewrite it in the readme file because I wrote the whole code based on this and now I have to switch to another player manager..

**Comment by ThePedroo** [comment]
You can keep using v3 for the time being. Aside from some bugs, like this one, it works flawlessly.
