### ISSUE TITLE
(Feature): Author Url Image

### ISSUE THREAD

**Issue by Root-Time** [1Lucas1apk/moonlink.js#106]
Is it possible to add the author image URL to MoonlinkTrack?

Or is there right now an another way to retrieve the author image url?

**Comment by ahmetceviik** [comment]
You can use **player.current.artworkUr**l

**Comment by ThePedroo** [comment]
You can get the track artwork, however the author artwork is not provided by LavaLink

**Comment by 1Lucas1apk** [comment]
the image of the author as pedro said is not provided by lavalink
