### ISSUE TITLE
(Bug): Stop does not work with autoPlay enabled

### ISSUE THREAD

**Issue by 1Lucas1apk** [1Lucas1apk/moonlink.js#115]
**Describe the bug**
Every time the stop function of the player with autoPlay active is called, instead of simply stopping playing, it starts playing another one afterwards

**Expected behavior**
stop playing and clear the queue

**Comment by xotakfr** [comment]
Thanks for reporting, I'll look into that asap

**Comment by xotakfr** [comment]
fixed by aac262f769860d8ebdd4f527256390b46403ec70
