### ISSUE TITLE
(Bug): Skip doesn't work with autoPlay enabled

### ISSUE THREAD

**Issue by ouwargui** [1Lucas1apk/moonlink.js#116]
**Describe the bug**
I don't know if this should be a feature request or a bug report, but player.skip() doesn't work if queue is empty and bot is auto playing.

**Expected behavior**
Skip should go to the next song.

Let me know if you need more info.

"discord.js": "^14.15.3"
"moonlink.js": "^4.0.2"

I'm using NodeLink.

**Comment by xotakfr** [comment]
Hey, I'll look into that. There's another bug currently affecting the autoplay feature so i'm working on it.

**Comment by xotakfr** [comment]
Fixed by aac262f
