### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by ddemile** [1Lucas1apk/moonlink.js#19]
Hello, i'm building a discord bot with typescript but i have some typescript erros :
![image](https://user-images.githubusercontent.com/104416229/234055479-c24eb307-f2a6-4781-82bd-c2755b381260.png)
![image](https://user-images.githubusercontent.com/104416229/234055600-e7581a09-513b-46f0-9251-80890ac4ef52.png)

**Comment by 1Lucas1apk** [comment]
Typing error, I will fix it, in the next version it will be fixed

**Comment by 1Lucas1apk** [comment]
This error was also fixed, have a great day, anything just create another issue
