### ISSUE TITLE
Player.connected is incorrect

### ISSUE THREAD

**Issue by ddemile** [1Lucas1apk/moonlink.js#20]
When I disconnect my bot from the channel, the Player.connected is still true

**Comment by 1Lucas1apk** [comment]
Hello, thanks for reporting, next version that is published I will fix this bug

**Comment by 1Lucas1apk** [comment]
Hello, a new version has been published and the bugs you reported have been fixed, have a great day :D

**Comment by ddemile** [comment]
ok thank you have a great day too
