### ISSUE TITLE
SearchResult.playlist is undefined

### ISSUE THREAD

**Issue by ddemile** [1Lucas1apk/moonlink.js#22]
SearchResult.playlist is wrong, in the code the property with the info of the playlist is SearchResult.playlistInfo not SearchResult.playlist who is undefined

**Comment by 1Lucas1apk** [comment]
Thanks for reporting, I'll fix it

**Comment by ddemile** [comment]
ok thk, just a question, is there a way to get the url and the thumbnail of a playlist ?

**Comment by 1Lucas1apk** [comment]
Internally I have not yet made any method to obtain
But from what I've researched, it's the same way as how to get it from a YouTube video 
https://i.ytimg.com/vi/id/hqdefault.jpg

**Comment by 1Lucas1apk** [comment]
It was tidy

**Comment by 1Lucas1apk** [comment]
Have a great day
