### ISSUE TITLE
Skipto is not working (sorry for creating that many issues)

### ISSUE THREAD

**Issue by ddemile** [1Lucas1apk/moonlink.js#23]
Using skipto is throwing an error saying that the position I provided is not valid but I know it's valid

![image](https://user-images.githubusercontent.com/104416229/235142753-9a3b8997-c69a-4a43-827f-2f99d6348a47.png)
![image](https://user-images.githubusercontent.com/104416229/235142859-a2ff2dce-e214-4f39-a65d-82985bc2c149.png)

**Comment by 1Lucas1apk** [comment]
you're right, I forgot to put "!"
```js
if (queue[position - 1])
   throw new Error(
    "[ @Moonlink/Player ]: the indicated position does not exist, make security in your code to avoid errors"
   )
```
