### ISSUE TITLE
Seek is not working

### ISSUE THREAD

**Issue by Tasty-Kiwi** [1Lucas1apk/moonlink.js#24]
When using `player.seek()`, it throws an error.
After further investigation, it seems that this.current is null in the method.
![image](https://user-images.githubusercontent.com/26067386/235198889-060c7817-6793-4f23-8491-225f24c482e4.png)
![image](https://user-images.githubusercontent.com/26067386/235198911-b4e2173e-aab4-410f-b1ad-96df17e3a223.png)

**Comment by ddemile** [comment]
This.current is null for me too, I use `moon.map.get("current")[guildId]` to get the current playing song

**Comment by 1Lucas1apk** [comment]
thank you very much for reporting, i will fix the error

**Comment by 1Lucas1apk** [comment]
It has been fixed, have a great day
