### ISSUE TITLE
skip error

### ISSUE THREAD

**Issue by dazzypark** [1Lucas1apk/moonlink.js#29]
```js
<player>.skip()
```

If you use the method above, the music will move on to the next song, but all the songs in the queue will disappear.

**Comment by 1Lucas1apk** [comment]
Thank you for reporting the error, I will analyze the codes to find the possible error, have a great day :D

**Comment by dazzypark** [comment]
Thanks for making the package. have a good day :)

**Comment by 1Lucas1apk** [comment]
Hello, I came to let you know that a new update has been posted and the skip has been fixed

**Comment by 1Lucas1apk** [comment]
Thank you very much for reporting the bug, have a great day :D
