### ISSUE TITLE
Problems if Lavalink crashes or shuts down

### ISSUE THREAD

**Issue by TinnerKun** [1Lucas1apk/moonlink.js#30]
![image](https://github.com/1Lucas1apk/moonlink.js/assets/45807795/e3c10e1d-719e-4553-a265-2c8c8140f05f)

If the Lavalink fails to connect, it will cause a bug that can shut down the node. In this case, connect first and shut down the Lavalink server.

**Comment by 1Lucas1apk** [comment]
Hello, have you checked if port 2333 is open? Try also putting 127.0.0.1 in place of host
