### ISSUE TITLE
Search with valid source doesn't work.

### ISSUE THREAD

**Issue by WilsontheWolf** [1Lucas1apk/moonlink.js#37]
It appears this code is causing the issue 
https://github.com/1Lucas1apk/moonlink.js/blob/v2/src/%40Moonlink/MoonlinkManager.ts#L465
I believe this should be ```searchIdentifier = `${sources[source] || "ytsearch"}:${query}`;``` but I'm not familiar with the code base enough to verify if this is the case.

**Comment by 1Lucas1apk** [comment]
Are the sources not working correctly?

**Comment by WilsontheWolf** [comment]
Yes. Its returning empty. 
![image](https://github.com/1Lucas1apk/moonlink.js/assets/33164598/3ef71112-dd49-405e-b4ea-62c2e56b6e57)
![image](https://github.com/1Lucas1apk/moonlink.js/assets/33164598/a5d15ec2-ac3d-412f-b559-7d9bc18d0ccd)

It works if using the actual query or leave it empty it works

**Comment by 1Lucas1apk** [comment]
Could you test the new version that was published today?

**Comment by WilsontheWolf** [comment]
The latest version fixes when using the source parameter, but seems to have broke when not using one.
![image](https://github.com/1Lucas1apk/moonlink.js/assets/33164598/a6b4799c-99eb-411d-90ed-657d287826e3)

**Comment by WilsontheWolf** [comment]
Looks like this also broke direct youtube URL's (returning empty) and direct http urls (now return a yt search instead of the url)

**Comment by 1Lucas1apk** [comment]
In the next version everything will be corrected, before publishing I will do something else in a part of the code

**Comment by 1Lucas1apk** [comment]
adjusted
