### ISSUE TITLE
Real Time Position Updates

### ISSUE THREAD

**Issue by WilsontheWolf** [1Lucas1apk/moonlink.js#38]
Right now, when I get the current tracks position it is just whatever the websocket sent last. This can (and will often)  be several seconds off. This can be seen when I executed this code:
`setInterval(() => console.log(lava.players.get(message.guild.id)?.current?.position), 1000)`
Which resulted in:
![image](https://github.com/1Lucas1apk/moonlink.js/assets/33164598/ef053a9c-56ce-46a1-811b-36a572cbecda)
As you can see, there isn't any change for several seconds.

You can get the desired effect like so (modified from https://github.com/WilsontheWolf/lavalink/blob/master/src/classes/Player.js#L80-L83)
```js
function calcPosition(player) {
    if (player.paused) return player.current.position;
    return player.current.position + (Date.now() - player.current.time); // Note this could cause some weird values if your clock is not synced with the lavalink instances clock. This is probably ignorable.
}
```

However, I would perfer to not have to write this code myself. I am wondering if we could have some sort of getter on player (because player.current doesn't have a class), so I can just call player.position to get the current position.  Thanks

**Comment by 1Lucas1apk** [comment]
Thanks for submitting this issue, I will add this idea to the codes

**Comment by 1Lucas1apk** [comment]
Thank you very much for the suggestion, the new version was published with the logic you created, if you want to check the code it is in this part of MoonlinkNodes https://github.com/1Lucas1apk/moonlink.js/blob/fd7d82d69d239ee9dfd8ab82a662d97e3db9c6d1/src/%40Moonlink/MoonlinkNodes.ts#L331C27-L331C27

**Comment by WilsontheWolf** [comment]
Sorry for the delay. Seems to be working great. Thank for making this.

**Comment by 1Lucas1apk** [comment]
You're welcome, have a great day
