### ISSUE TITLE
reconnect after lavalink server restart

### ISSUE THREAD

**Issue by Turkidev** [1Lucas1apk/moonlink.js#40]
how can i make the bot auto reconnect to lavalink server after the server restart
i'm getting this error when the server restart [ @Moonlink/Manager ]: No lavalink server connected

**Comment by Nansess** [comment]
```
const options = {
  clientName: "MyClient",
  reconnectAttempts: 5,
  retryTime: 3000,
  retryAmount: 3,
  resumeKey: "myResumeKey",
  resumeTimeout: 5000,
  autoResume: true,
  sortNode: "memory"
};

// Use the created options object to initialize a MoonlinkManager
const moonlinkManager = new MoonlinkManager(nodes, options, _sPayload);

```

In the Moonlink documentation (https://moonlink.js.org/classes#options), 'reconnect attempts' allows you to configure the number of reconnection attempts in your manager options. You can also set the retry time. If you do not have a resume key, simply remove 'auto-resume' and the resume key.

**Comment by Turkidev** [comment]
what is myResumeKey?

**Comment by Turkidev** [comment]
Error: connect ECONNREFUSED ip:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
Error: connect ECONNREFUSED ip:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
TypeError: [ @Moonlink/Manager ]: No lavalink server connected
    at MoonlinkManager.sortByUsage (/var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/node_modules/moonlink.js/dist/src/@Moonlink/MoonlinkManager.js:98:19)
    at MoonlinkManager.create (/var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/node_modules/moonlink.js/dist/src/@Moonlink/MoonlinkManager.js:395:35)
    at Client.<anonymous> (/var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/src/main.js:3554:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by 1Lucas1apk** [comment]
The problem is that moonlink is not connecting to the server

**Comment by 1Lucas1apk** [comment]
Have you checked that the node information is correct?

**Comment by Turkidev** [comment]
yes the lavalink works
if the server restarted it loses the connection and don’t reconnect

**Comment by 1Lucas1apk** [comment]
I'll look into it, and I'll come back in a bit.

**Comment by 1Lucas1apk** [comment]
Could you take some prints of the logs?, just to confirm something

**Comment by Turkidev** [comment]
Error: connect ECONNREFUSED lavalinkserver:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
Error: connect ECONNREFUSED lavalinkserver:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
TypeError: [ @Moonlink/Manager ]: No lavalink server connected
    at MoonlinkManager.sortByUsage (/var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/node_modules/moonlink.js/dist/src/@Moonlink/MoonlinkManager.js:98:19)
    at MoonlinkManager.create (/var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/node_modules/moonlink.js/dist/src/@Moonlink/MoonlinkManager.js:398:35)
    at Client.<anonymous> (/var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/src/main.js:3573:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Turkidev** [comment]
TypeError: [ @Moonlink/Manager ]: No lavalink server connected
when i try to start a song

**Comment by 1Lucas1apk** [comment]
I found the possible error, I will correct it and publish a new version

**Comment by 1Lucas1apk** [comment]
Hello, could you update the package and test again to see if the problem occurs?

**Comment by Turkidev** [comment]
When i try to add playlist I’m getting this error
0|part_0  | TypeError: Cannot read properties of undefined (reading 'reduce')
0|part_0  |     at /var/lib/pterodactyl/volumes/cb0089be-9653-44c2-9654-41b325a660ab/node_modules/moonlink.js/dist/src/@Moonlink/MoonlinkManager.js:295:51
0|part_0  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Turkidev** [comment]
this is my code

`    async search(options) {
        return new Promise(async (resolve, reject) => {
            try {
                if (!options) {
                    throw new Error("[ @Moonlink/Manager ]: the search option has to be in string format or in an array");
                }
                let query;
                let source;
                if (typeof options === "object") {
                    query = options.query;
                    source = options.source;
                }
                else {
                    query = options;
                }
                if (source && typeof source !== "string") {
                    throw new Error("[ @Moonlink/Manager ]: the source option has to be in string format");
                }
                if (typeof query !== "string" && typeof query !== "object") {
                    throw new Error("[ @Moonlink/Manager ]: (search) the search option has to be in string or array format");
                }
                const sources = {
                    youtube: "ytsearch",
                    youtubemusic: "ytmsearch",
                    soundcloud: "scsearch",
                    spotify: "spotify",
                    spsearch: "spsearch",
                };
                if (this.spotify.isSpotifyUrl(query)) {
                    return resolve(await this.spotify.resolve(query));
                }
                let searchIdentifier = query.startsWith("http://") || query.startsWith("https://")
                    ? query
                    : source && sources[source]
                        ? `${sources[source]}:${query}`
                        : `ytsearch:${query}`;
                const params = new URLSearchParams({ identifier: searchIdentifier });
                const res = await this.sortByUsage("memory")[0].request("loadtracks", params);
                if (["error", "empty", "LOAD_FAILED", "NO_MATCHES"].includes(res.loadType)) {
                    this.emit("debug", "[ @Moonlink/Manager ]: not found or there was an error loading the track");
                    return resolve(res);
                }
                if (["track", "TRACK_LOADED"].includes(res.loadType)) {
                    res.data = [res.loadType === "TRACK_LOADED" ? res.tracks : res.data];
                }
                if (["playlist", "PLAYLIST_LOADED"].includes(res.loadType)) {
                    res.data = {
                        tracks: res.tracks,
                        info: res.playlistInfo,
                    };
                    res.playlistInfo = {
                        duration: res.data.tracks.reduce((acc, cur) => acc + cur.info.length, 0),
                        name: res.data.info.name,
                        selectedTrack: res.data.info.selectedTrack,
                    };
                    res.pluginInfo = res.data.pluginInfo;
                    res.data = [...res.data.tracks];
                }
                if (res.loadType === "SEARCH_RESULT" && res.tracks) {
                    res.data = res.tracks;
                }
                res.tracks = null;
                const tracks = res.data.map((x) => new index_1.MoonlinkTrack(x));
                resolve({
                    ...res,
                    tracks,
                });
            }
            catch (error) {
                this.emit("debug", "[ @Moonlink/Manager ]: An error occurred: " + error.message);
                reject(error);
            }
        });
    }`

**Comment by Turkidev** [comment]
async search(options) {
        return new Promise(async (resolve, reject) => {
            try {
                if (!options) {
                    throw new Error("[ @Moonlink/Manager ]: the search option has to be in string format or in an array");
                }
                let query;
                let source;
                if (typeof options === "object") {
                    query = options.query;
                    source = options.source;
                }
                else {
                    query = options;
                }
                if (source && typeof source !== "string") {
                    throw new Error("[ @Moonlink/Manager ]: the source option has to be in string format");
                }
                if (typeof query !== "string" && typeof query !== "object") {
                    throw new Error("[ @Moonlink/Manager ]: (search) the search option has to be in string or array format");
                }
                const sources = {
                    youtube: "ytsearch",
                    youtubemusic: "ytmsearch",
                    soundcloud: "scsearch",
                    spotify: "spotify",
                    spsearch: "spsearch",
                };
                if (this.spotify.isSpotifyUrl(query)) {
                    return resolve(await this.spotify.resolve(query));
                }
                let searchIdentifier = query.startsWith("http://") || query.startsWith("https://")
                    ? query
                    : source && sources[source]
                        ? `${sources[source]}:${query}`
                        : `ytsearch:${query}`;
                const params = new URLSearchParams({ identifier: searchIdentifier });
                const res = await this.sortByUsage("memory")[0].request("loadtracks", params);
                if (["error", "empty", "LOAD_FAILED", "NO_MATCHES"].includes(res.loadType)) {
                    this.emit("debug", "[ @Moonlink/Manager ]: not found or there was an error loading the track");
                    return resolve(res);
                }
                if (["track", "TRACK_LOADED"].includes(res.loadType)) {
                    res.data = [res.loadType === "TRACK_LOADED" ? res.tracks : res.data];
                }
                if (["playlist", "PLAYLIST_LOADED"].includes(res.loadType)) {
                    res.data = {
                        tracks: res.tracks,
                        info: res.playlistInfo,
                    };
                    res.playlistInfo = {
                        duration: res.data.tracks.reduce((acc, cur) => acc + cur.info.length, 0),
                        name: res.data.info.name,
                        selectedTrack: res.data.info.selectedTrack,
                    };
                    res.pluginInfo = res.data.pluginInfo;
                    res.data = [...res.data.tracks];
                }
                if (res.loadType === "SEARCH_RESULT" && res.tracks) {
                    res.data = res.tracks;
                }
                res.tracks = null;
                const tracks = res.data.map((x) => new index_1.MoonlinkTrack(x));
                resolve({
                    ...res,
                    tracks,
                });
            }
            catch (error) {
                this.emit("debug", "[ @Moonlink/Manager ]: An error occurred: " + error.message);
                reject(error);
            }
        });
    }

**Comment by Turkidev** [comment]
moonlink.js@2.13.72 the playlist works
moonlink.js@2.14.88 the playlist  don't work

**Comment by 1Lucas1apk** [comment]
What version of lavalink?

**Comment by Turkidev** [comment]
4.0.0-beta.4

**Comment by 1Lucas1apk** [comment]
I will analyze :)

**Comment by Turkidev** [comment]
and i have more than 5 lavalink servers
if one of them is down how can i make the bot change the server?

**Comment by 1Lucas1apk** [comment]
I think I have to do this internally, but moonlink has a system to autoResume when lavalink returns

**Comment by Turkidev** [comment]
can i add the lavalink server’s details into array and when the server disconnect the bot make a new connection to another one?

**Comment by 1Lucas1apk** [comment]
The search in the new version that I published was fixed, and in the other one there will be a system to move players from the inactive node to another
