### ISSUE TITLE
check lavalink status

### ISSUE THREAD

**Issue by Turkidev** [1Lucas1apk/moonlink.js#41]
how can i make the bot check the server status if its online or not
and if its online how many clients connected to it

**Comment by 1Lucas1apk** [comment]
Hello, I will make a basic code and send it to you

**Comment by 1Lucas1apk** [comment]
```js
  const onlineNodes = client.moon.nodes;
  let statusMessage = 'Server Status:\n';

  for (const [nodeIdentifier, node] of onlineNodes) {
    const totalPlayers = node.stats.players;
    const isOnline = node.isConnected;

    statusMessage += `Node ${nodeIdentifier} is ${isOnline ? 'online' : 'offline'}.`;
    if (isOnline) {
      statusMessage += ` Total connected players: ${totalPlayers}`;
    }
    statusMessage += '\n';
  }

  message.reply(statusMessage);
```

I hope this helps you :)

**Comment by Turkidev** [comment]
can i add more then 1 node?

**Comment by Turkidev** [comment]
my method is
const lavalinkservers = [
  {
    host: 'ip',
    port: 2333,
    secure: false,
    password: 'password'
  }
];

**Comment by Turkidev** [comment]
stats: {
  players: 0,
  playingPlayers: 0,
  uptime: 0,
  memory: { free: 0, used: 0, allocated: 0, reservable: 0 },
  cpu: { cores: 0, systemLoad: 0, lavalinkLoad: 0 },
  frameStats: { sent: 0, nulled: 0, deficit: 0 }
},
