### ISSUE TITLE
status are 0

### ISSUE THREAD

**Issue by Turkidev** [1Lucas1apk/moonlink.js#42]
stats: {
  players: 0,
  playingPlayers: 0,
  uptime: 0,
  memory: { free: 0, used: 0, allocated: 0, reservable: 0 },
  cpu: { cores: 0, systemLoad: 0, lavalinkLoad: 0 },
  frameStats: { sent: 0, nulled: 0, deficit: 0 }
},

**Comment by 1Lucas1apk** [comment]
Is the lavalink connected?

**Comment by Turkidev** [comment]
yes the server is online and working
i have 2 players

{
  players: 0,
  playingPlayers: 0,
  uptime: 0,
  memory: { free: 0, used: 0, allocated: 0, reservable: 0 },
  cpu: { cores: 0, systemLoad: 0, lavalinkLoad: 0 },
  frameStats: { sent: 0, nulled: 0, deficit: 0 }
}
{
  frameStats: null,
  players: 0,
  playingPlayers: 0,
  uptime: 81767,
  memory: {
    free: 261004328,
    used: 359752664,
    allocated: 620756992,
    reservable: 32178700288
  },
  cpu: {
    cores: 16,
    systemLoad: 0.5703415069337846,
    lavalinkLoad: 0.002892412322179521
  }
}

**Comment by 1Lucas1apk** [comment]
So one is not catching on?

**Comment by Turkidev** [comment]
yes and the other show players 0

**Comment by 1Lucas1apk** [comment]
And in the lavalink logs, the connection established with "Moonlink/(Version)" appears?

**Comment by Turkidev** [comment]
Yes
And the music is working

**Comment by 1Lucas1apk** [comment]
You could go to the support server, I can help you better there, here spam webhook on some servers

**Comment by Turkidev** [comment]
where is the support server
the one in the package is invalid

**Comment by 1Lucas1apk** [comment]
https://discord.com/invite/D639NjBQ

Try using this invitation
