### ISSUE TITLE
(Bug): Queue loop not working properly

### ISSUE THREAD

**Issue by xotakfr** [1Lucas1apk/moonlink.js#77]
**Describe the bug**
When enabling queue loop, only the first track of the queue is repeated. The tracks waiting in queue aren't played.

**To Reproduce**
1 - Queue 2+ tracks
2 - Enable loop with `player.setLoop(2)`
3 - Only the first track of the queue is played

**Expected behavior**
The full queue is played repeatedly

**Screenshots**
None

**Additional context**
Tried to edit to code a bit. It seems that `@Entities/MoonlinkNode.js:339` is problematic (`player.current = queue.shift();`). Removing that line successfully make the queue loop, but it adds each song once each loop (ie. 1st loop : each song is played one time, 2nd loop : each song is played 2 times, ...)

**Comment by 1Lucas1apk** [comment]
Sorry for the delay, I'll investigate the problems and fix them soon :)

**Comment by 1Lucas1apk** [comment]
Bug confirmed, I tried to test it before, but my lavalinks were giving 403 and I tested using nodelink

**Comment by xotakfr** [comment]
Tested and working on m sad, thanks for the fix

**Comment by 1Lucas1apk** [comment]
I'm still going to do some cleaning

**Comment by 1Lucas1apk** [comment]
I'm asking for the IP and Port of a machine to finish testing and also fix the shuffle together.

**Comment by xotakfr** [comment]
While we're here, is it possible to have a look at the shuffle ? It doesn't seem to work either. Even if I know that you're not the person that wrote that code

**Comment by 1Lucas1apk** [comment]
Yes, I will, I will do the analysis and modify the shuffle, so that it works as it should

**Comment by 1Lucas1apk** [comment]
Fixed
